# Generated by Django 5.1.3 on 2024-11-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('stampdatetime', models.DateField(auto_now=True)),
                ('item_name', models.TextField(max_length=50)),
                ('rate', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'item_master',
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
